### ISSUE TITLE
Fix timer class

### ISSUE THREAD

**Issue by adi-g15** [AdityaGupta150/sudokuSolver_Optimized#2]
Currently the build is failing, due to util::timer class.
That can be removed, though it would be preferred that commented, after fixing the util::timer class.
You can take help from a correctly working util::timer class from the [timer.hpp](https://github.com/AdityaGupta150/CPP_Util).

It is relatively simple, but the beginner will also get to have a look into the automated builds, and the satisfaction after fixing a build error :smile:

**Comment by abraham-john-paul** [comment]
Hi can i work on this?

**Comment by adi-g15** [comment]
@abraham-john-paul Sorry friend it's already fixed by #3 , but you are always welcome to find something to fix in the codebase, i believe its small enough for bug picking, and at same time fixing a bug is really a great achievement. 😃 🎉

**Comment by adi-g15** [comment]
I will close this issue, and will create some other after seeing through, and where i see a need, so you can keep an eye to a comment referencing you, and you can reply too 👍🏽
